apiVersion: v1
kind: Service
metadata:
  name: oracle-xe
  namespace: spark-etl
  labels:
    app: oracle-xe
spec:
  type: ClusterIP
  selector:
    app: oracle-xe
  ports:
    - name: listener
      port: 1521
      targetPort: 1521

