apiVersion: v1
kind: Pod
metadata:
  name: pvc-debug
  namespace: spark-etl-mysql
spec:
  containers:
  - name: debug
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: output
      mountPath: /output
  volumes:
  - name: output
    persistentVolumeClaim:
      claimName: etl-output-pvc